import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { EulerAnalysis, HamiltonAnalysis } from '../types/graph';
import { CheckCircle, XCircle, HelpCircle, Play, ArrowRight, Lightbulb, BookOpen, Route, Compass } from 'lucide-react';
export const AnalysisCards = ({ eulerAnalysis, hamiltonAnalysis, activeTab, onSelectTab, onRunSimulation, }) => {
    return (_jsxs("div", { className: "bg-white border border-slate-200/90 rounded-2xl overflow-hidden shadow-xs flex flex-col", children: [_jsxs("div", { className: "grid grid-cols-2 bg-slate-50/80 border-b border-slate-200/80", children: [_jsxs("button", { onClick: () => onSelectTab('euler'), className: `flex items-center justify-center gap-2 py-3 px-4 text-xs font-semibold border-b-2 transition-all cursor-pointer ${activeTab === 'euler'
                            ? 'border-indigo-600 text-indigo-700 bg-white'
                            : 'border-transparent text-slate-600 hover:text-slate-900 hover:bg-slate-100/60'}`, children: [_jsx(Route, { className: "w-4 h-4" }), _jsx("span", { children: "Ki\u1EC3m tra Euler" }), eulerAnalysis.hasEuler ? (_jsx("span", { className: "w-2 h-2 rounded-full bg-emerald-500 ml-1" })) : (_jsx("span", { className: "w-2 h-2 rounded-full bg-slate-300 ml-1" }))] }), _jsxs("button", { onClick: () => onSelectTab('hamilton'), className: `flex items-center justify-center gap-2 py-3 px-4 text-xs font-semibold border-b-2 transition-all cursor-pointer ${activeTab === 'hamilton'
                            ? 'border-indigo-600 text-indigo-700 bg-white'
                            : 'border-transparent text-slate-600 hover:text-slate-900 hover:bg-slate-100/60'}`, children: [_jsx(Compass, { className: "w-4 h-4" }), _jsx("span", { children: "Ki\u1EC3m tra Hamilton" }), hamiltonAnalysis.hasCycle ? (_jsx("span", { className: "w-2 h-2 rounded-full bg-emerald-500 ml-1" })) : (_jsx("span", { className: "w-2 h-2 rounded-full bg-slate-300 ml-1" }))] })] }), _jsx("div", { className: "p-4 flex flex-col gap-3.5", children: activeTab === 'euler' ? (_jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("div", { className: `p-3.5 rounded-xl border flex flex-col gap-2 ${eulerAnalysis.type === 'circuit'
                                ? 'bg-emerald-50/80 border-emerald-200 text-emerald-950'
                                : eulerAnalysis.type === 'path'
                                    ? 'bg-sky-50/80 border-sky-200 text-sky-950'
                                    : 'bg-rose-50/80 border-rose-200 text-rose-950'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 font-bold text-sm", children: [eulerAnalysis.hasEuler ? (_jsx(CheckCircle, { className: "w-4 h-4 text-emerald-600 shrink-0" })) : (_jsx(XCircle, { className: "w-4 h-4 text-rose-600 shrink-0" })), _jsxs("span", { children: [eulerAnalysis.type === 'circuit' && 'Có Chu trình Euler', eulerAnalysis.type === 'path' && 'Có Đường đi Euler', eulerAnalysis.type === 'none' && 'Không có Chu trình hay Đường đi Euler'] })] }), _jsxs("span", { className: "text-[11px] px-2 py-0.5 rounded-full font-mono font-semibold bg-white/80 border border-slate-200/80 text-slate-700 shadow-2xs", children: [eulerAnalysis.type === 'circuit' && 'Eulerian Circuit', eulerAnalysis.type === 'path' && 'Eulerian Trail', eulerAnalysis.type === 'none' && 'Non-Eulerian'] })] }), _jsx("p", { className: "text-xs text-slate-700 leading-relaxed font-medium", children: eulerAnalysis.reason })] }), _jsxs("div", { className: "bg-slate-50 border border-slate-200/80 rounded-xl p-3 text-xs flex flex-col gap-2", children: [_jsxs("span", { className: "font-semibold text-slate-800 flex items-center gap-1.5", children: [_jsx(Lightbulb, { className: "w-3.5 h-3.5 text-amber-500" }), "Ki\u1EC3m tra \u0110\u1ECBnh l\u00FD Euler:"] }), _jsxs("ul", { className: "space-y-1.5 text-slate-700", children: [_jsxs("li", { className: "flex items-start gap-2", children: [eulerAnalysis.isAllConnectedNonZero ? (_jsx(CheckCircle, { className: "w-3.5 h-3.5 text-emerald-600 mt-0.5 shrink-0" })) : (_jsx(XCircle, { className: "w-3.5 h-3.5 text-rose-600 mt-0.5 shrink-0" })), _jsxs("span", { children: [_jsx("strong", { className: "text-slate-900", children: "T\u00EDnh li\u00EAn th\u00F4ng:" }), ' ', eulerAnalysis.isAllConnectedNonZero
                                                            ? 'Liên thông trên tất cả đỉnh có bậc > 0.'
                                                            : `Không liên thông (${eulerAnalysis.componentsCountNonZero} thành phần).`] })] }), _jsxs("li", { className: "flex items-start gap-2", children: [_jsx("span", { className: `w-4 h-4 rounded-full flex items-center justify-center text-[10px] font-bold mt-0.5 shrink-0 ${eulerAnalysis.oddDegreeCount === 0 || eulerAnalysis.oddDegreeCount === 2
                                                        ? 'bg-emerald-100 text-emerald-700'
                                                        : 'bg-rose-100 text-rose-700'}`, children: eulerAnalysis.oddDegreeCount }), _jsxs("span", { children: [_jsx("strong", { className: "text-slate-900", children: "S\u1ED1 \u0111\u1EC9nh b\u1EADc l\u1EBB:" }), " ", eulerAnalysis.oddDegreeCount, " \u0111\u1EC9nh.", ' ', eulerAnalysis.oddDegreeCount === 0 && 'Tất cả đỉnh đều bậc chẵn → Chu trình Euler.', eulerAnalysis.oddDegreeCount === 2 && (_jsxs(_Fragment, { children: ["\u0110\u00FAng 2 \u0111\u1EC9nh b\u1EADc l\u1EBB (", eulerAnalysis.oddDegreeVertices.map(v => v.label).join(', '), ") \u2192 \u0110\u01B0\u1EDDng \u0111i Euler."] })), eulerAnalysis.oddDegreeCount > 2 && (_jsxs("span", { className: "text-rose-700", children: ["Nhi\u1EC1u h\u01A1n 2 \u0111\u1EC9nh b\u1EADc l\u1EBB (", eulerAnalysis.oddDegreeVertices.map(v => v.label).join(', '), ")."] }))] })] })] })] }), _jsxs("button", { onClick: () => onRunSimulation('euler'), disabled: !eulerAnalysis.hasEuler, className: "w-full flex items-center justify-center gap-2 py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-100 disabled:text-slate-400 text-white font-semibold text-xs rounded-xl transition-all shadow-xs cursor-pointer disabled:cursor-not-allowed", children: [_jsx(Play, { className: "w-3.5 h-3.5" }), _jsx("span", { children: eulerAnalysis.hasEuler
                                        ? 'Mô phỏng thuật toán Hierholzer từng bước'
                                        : 'Không thể mô phỏng (Đồ thị không Euler)' })] })] })) : (_jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("div", { className: `p-3.5 rounded-xl border flex flex-col gap-2 ${hamiltonAnalysis.hasCycle
                                ? 'bg-emerald-50/80 border-emerald-200 text-emerald-950'
                                : 'bg-slate-50 border-slate-200 text-slate-800'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 font-bold text-sm", children: [hamiltonAnalysis.hasCycle ? (_jsx(CheckCircle, { className: "w-4 h-4 text-emerald-600 shrink-0" })) : (_jsx(HelpCircle, { className: "w-4 h-4 text-amber-600 shrink-0" })), _jsx("span", { children: hamiltonAnalysis.hasCycle
                                                        ? 'Tìm thấy Chu trình Hamilton'
                                                        : 'Không tìm thấy Chu trình Hamilton' })] }), _jsx("span", { className: "text-[11px] px-2 py-0.5 rounded-full font-mono font-semibold bg-white/80 border border-slate-200/80 text-slate-700 shadow-2xs", children: hamiltonAnalysis.hasCycle ? 'Hamiltonian' : 'Non-Hamiltonian' })] }), hamiltonAnalysis.hasCycle && (_jsxs("div", { className: "flex items-center gap-1.5 text-xs font-mono text-emerald-800 overflow-x-auto py-1", children: [_jsx("strong", { children: "Chu tr\u00ECnh:" }), hamiltonAnalysis.cycleLabels.map((lbl, idx) => (_jsxs(React.Fragment, { children: [idx > 0 && _jsx(ArrowRight, { className: "w-3 h-3 text-emerald-500 shrink-0" }), _jsx("span", { className: "px-1.5 py-0.5 bg-emerald-100 rounded border border-emerald-200 text-emerald-800 font-bold", children: lbl })] }, idx)))] })), _jsx("p", { className: "text-xs text-slate-700 leading-relaxed font-medium", children: hamiltonAnalysis.reason || 'Dùng thuật toán quay lui (Backtracking) để tìm chu trình qua tất cả các đỉnh.' })] }), _jsxs("div", { className: "bg-slate-50 border border-slate-200/80 rounded-xl p-3 text-xs flex flex-col gap-2", children: [_jsxs("span", { className: "font-semibold text-slate-800 flex items-center gap-1.5", children: [_jsx(BookOpen, { className: "w-3.5 h-3.5 text-indigo-600" }), "\u0110\u00E1nh gi\u00E1 L\u00FD thuy\u1EBFt:"] }), _jsx("ul", { className: "space-y-1.5 text-slate-700", children: hamiltonAnalysis.theoreticalNotes.map((note, idx) => (_jsxs("li", { className: "flex items-start gap-2", children: [_jsx("span", { className: "text-indigo-600 font-bold shrink-0", children: "\u2022" }), _jsx("span", { children: note })] }, idx))) }), _jsxs("div", { className: "mt-1 pt-2 border-t border-slate-200 text-[11px] text-slate-500 leading-relaxed", children: [_jsx("strong", { className: "text-slate-700", children: "L\u01B0u \u00FD:" }), " B\u00E0i to\u00E1n t\u00ECm chu tr\u00ECnh Hamilton thu\u1ED9c l\u1EDBp NP-\u0111\u1EA7y \u0111\u1EE7 (NP-complete). Thu\u1EADt to\u00E1n quay lui duy\u1EC7t v\u00E9t c\u1EA1n \u0111\u1EC3 t\u00ECm ki\u1EBFm chu tr\u00ECnh ho\u1EB7c ch\u1EE9ng th\u1EF1c kh\u00F4ng t\u1ED3n t\u1EA1i."] })] }), _jsxs("button", { onClick: () => onRunSimulation('hamilton'), className: "w-full flex items-center justify-center gap-2 py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs rounded-xl transition-all shadow-xs cursor-pointer", children: [_jsx(Play, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "M\u00F4 ph\u1ECFng thu\u1EADt to\u00E1n Quay lui (Backtracking)" })] })] })) })] }));
};
//# sourceMappingURL=AnalysisCards.js.map